<?php

return [

    'MASTERSINDIA_BASEURL' => env('MASTERSINDIA_BASEURL', 'default'),
	'MASTERSINDIA_PROD_BASEURL' => env('MASTERSINDIA_PROD_BASEURL', 'default'),
    'MASTERSINDIA_CLIENT_ID' => env('MASTERSINDIA_CLIENT_ID', 'default'),
    'MASTERSINDIA_CLIENT_SECRET' => env('MASTERSINDIA_CLIENT_SECRET', 'default'),
	'MASTERSINDIA_PROD_CLIENT_ID' => env('MASTERSINDIA_PROD_CLIENT_ID', 'default'),
    'MASTERSINDIA_PROD_CLIENT_SECRET' => env('MASTERSINDIA_PROD_CLIENT_SECRET', 'default'),
    'COMP_EMAIL' => env('COMP_EMAIL', 'default'),

];
