<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Asset_non_currents extends Model
{
    use HasFactory;
	
	protected $fillable = [
        // Existing fields
        'pid',
        'asid',
		'addedby',
		'nonCurrentAssetType',
		'asset_date_nca',
		'voucher_type_nca',
		'ledger_nca',
		'amt_nca',
		'debitcredit_nca',
		'due_date_nca',
		'invoice_no_nca',
		'gst_rate_nca',
		'tds_ded_nca',
		'interest_nca',
		'depreciations_nca',
		'supporting_doc_nca',
		
		'fixedAssetCategory',
		'assetName',
		'assetCategory',
		'assetPurchaseDate',
		'assetPurchaseCost',
		'assetInvoiceNumber',
		'assetVendorName',
		'assetDepreciationMethod',
		'assetUsefulLife',
		'assetSalvageValue',
		'assetDepreciationRate',
		'assetLocation',
		'assetCapitalizationDate',
		'assetTagCode',
		'assetWarrantyDetails',
		'assetStatus',

		'intangibleAssetCategory',
		'intangibleAssetName',
		'intangibleAssetType',
		'intangibleAcquisitionDate',
		'intangibleAcquisitionCost',
		'intangibleUsefulLife',
		'intangibleAmortisationMethod',
		'intangibleResidualValue',
		'intangibleImpairmentFlag',
		'intangibleAccumulatedAmortisation',
		'intangibleImpairmentLoss',
		'intangibleRevaluationAdjustment',
		'intangibleStatus',

		'capitalWIPCategory',
		'projectName',
		'wipAssetCategory',
		'projectWorkOrderRefNo',
		'dateOfEntry',
		'vendorSupplierName',
		'invoiceReferenceNo',
		'natureOfExpense',
		'expenseAmount',
		'gstAmount',
		'totalCost',
		'paymentDate',
		'modeOfPayment',
		'status',

		'nonCurrentAssetTypeSec',
		'nonCurrentAssetName',
		'nonCurrentInvestType',
		'nonCurrentAssetDate',
		'nonCurrentAssetAmount',
		'nonCurrentAssetFaceValue',
		'nonCurrentAssetUnits',
		'nonCurrentAssetPurchasePrice',
		'nonCurrentAssetBrokerage',
		'nonCurrentAssetModeOfHolding',
		'nonCurrentAssetExpectedReturn',
		'nonCurrentAssetLinkedLedger',
		'nonCurrentAssetMaturityDate',
		'nonCurrentAssetRevaluationDate',
		'nonCurrentAssetNotes',

		'deferredTaxAssetType',
		'deferredTaxAssetRate',
		'deferredTaxAssetStandard',
		'financialYear',
		'bookValue',
		'taxBase',
		'timingDifference',
		'natureOfDifference',
		'reversalPeriod',
		'previouslyRecognizedDTA',

		'longTermLoanType',
		'longTermLoanPartyName',
		'longTrmLoanType',
		'longTermLoanPurpose',
		'longTermLoanAmount',
		'longTermLoanDisbursementDate',
		'longTermLoanTenure',
		'longTermLoanRepaymentTerms',
		'longTermLoanInterestRate',
		'longTermLoanInterestAccrualMethod',
		'longTermLoanSecurityOffered',
		'longTermLoanBalanceAsOfDate',
		'longTermLoanWriteOffProvision',
		'longTermLoanGLAccountMapping',

		'otherNonCurrentAssetType',
		'otherNonCurrAssetType',
		'otherNonCurrentAssetDescription',
		'otherNonCurrentAssetParty',
		'otherNonCurrentAssetAmount',
		'otherNonCurrentAssetTransactionDate',
		'otherNonCurrentAssetExpectedRealizationDate',
		'otherNonCurrentAssetLinkedAsset',
		'otherNonCurrentAssetClassificationTag',
		'otherNonCurrentAssetAccountingLedger',
		'otherNonCurrentAssetStatus',
		'otherNonCurrentAssetDocument',

        'created_at',
        'updated_at',
       
    ];
}
