<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Asset_currents extends Model
{
    use HasFactory;
	
	protected $fillable = [
        // Existing fields
        'prid',
        'aid',
		'uid',
		'currentAssetType',
		'asset_date',
		'voucher_type',
		'ledger',
		'amt',
		'debitcredit',
		'due_date',
		'invoice_no',
		'gst_rate',
		'tds_ded',
		'interest',
		'depreciations',
		'supporting_doc',
		
		'current_investmentsType',
		'instrumentname',
		'investmentamount',
		'purchasedate',
		'maturitydate',
		'marketvalue',
		'accounthead',
		'linkedbankaccount',
		'incomeearned',

		'InventoriesType',
		'InventoriesName',
		'itemcategory',
		'openingquantity',
		'openingrate',
		'purchaseqty',
		'purchaserate',
		'salesqty',
		'closingquantity',
		'valuationMethod',
		'rateofclosingstock',
		'closingstockvalue',

		'tradeReceivablesType',
		'receivableDate',
		'receivableAmount',

		'shortTermLoansType',
		'beneficiaryname',
		'ledgeraccount',
		'advanceamount',
		'advancedate',
		'excerealidate',
		'pur_remark',
		'tdsdeducted',
		'adjustats',
		'prod_image',
		'vendornameId',
		'vendorledaccount',
		'advancepayamount',
		'advancepaydate',
		'modeofpay',
		'invoiceno',
		'tdsdeduct',
		'gstcomponent',
		'vendor_remark',
		'settlestats',
		'adjudate',
		'unadadvbalance',

		'unbilledRevenueType',
		'clientname',
		'projectreference',
		'ser_startdate',
		'ser_enddate',
		'recognidate',
		'contvalue',
		'perceofwork',
		'totalbilleddate',
		'worklogs',
		'progressstatus',
		'billingterms',
		'revenuerecogini',

		'interestAccrueddueType',
		'lenderdeposittype',
		'lendername',
		'principalamount',
		'interestrate',
		'interestrateAnnual',
		'loanstartdate',
		'maturitydatelender',
		'repaymentfrequency',
		'interestpaymentduedates',
		'interestpayableaccount',
		'interestaccruedaccount',
		'accrualbasis',
		'lastinterestpaiddate',
		'calculationmethod',
		'simpleinterest',
		'compoundinterest',

		'gstReceivableType',
		'gstDate',
		'currGstAmount',

		'tdsReceivableType',
		'tds_option',
		'tds_percentage',
		'invoice_date',
		'payment_date',
		'invoice_amount',
		'tds_amount',
		'tds_section',
		'tds_rate',
		'tds_deduamount',
		'tds_threamount',
		'tds_limitsection',

		'prepaidExpensesType',
		'expcategory',
		'vendorname',
		'totalexpamount',
		'exp_paymentdate',
		'expstartdate',
		'expenddate',
		'prepaidperiod',
		'exprecognitionfreq',
		'accountingledgerhead',

		'groupCompanyReceivablesType',
		'transactiondate',
		'groupcompanyname',
		'transactiontype',
		'invno',
		'debitCreditFlag',
		'amount',
		'currency',
		'paymentterms',
		'settledamount',
		'tds_deduct',
		'intercompanytransfertag',
		'remarks',

		'otherCurrentAssetsType',
		'prepaidExpenses',
		'advanceToSuppliers',
		'inputGSTCredit',
		'tdsReceivable',
		'otherAdvances',
		'unbilledRevenue',
		'securityDeposits',
		'deferredCharges',
		'accruedInterestReceivable',
		'otherCurrentAssetsDescription',

		'grantSubsidyReceivableType',
		'grantSubsidyType',
		'sanctionOrderNo',
		'sanctionDate',
		'amountSanctioned',
		'amountReceived',
		'balanceReceivable',
		'recognitionCriteria',
		'expectedReceiptDate',
		'linkedAssetExpense',
		'tds_Deducted',
		'governmentDepartment',

		'deferredRevenueType',
		'customerName',
		'invoiceDate',
		'totalInvoiceAmount',
		'deferredAmount',
		'revenueRecognitionPeriod',
		'serviceStartDate',
		'serviceEndDate',
		'recognitionFrequency',
		'deferredRevenueAccount',
		'revenueAccount',

		'royaltyReceivablesType',
		'royaltyPartyName',
		'royaltyAgreementID',
		'royaltyType',
		'royaltyPercentage',
		'salesUsageAmount',
		'minGuaranteeAmount',
		'billingCycle',
		'royaltyDueDate',
		'royaltyTDSDeducted',
		'royaltyPaymentStatus',
		'royaltyRemarks',
		'royaltyAccountHead',

		'workInProgressType',
		'projectID',
		'orderBatchNo',
		'startDate',
		'expectedCompletionDate',
		'workStatus',
		'completionStage',
		'rawMaterialConsumed',
		'directLabourCost',
		'directOverhead',
		'allocatedIndirectExpenses',
		'openingWIPInventory',
		'rawMaterialsIssued',
		'goodsMovedToFinishedStock',
		'costMethod',
		'valuationBasis',
		'hoursWorked',
		'milestoneBilling',

		'cashEquivalentsType',
		'cashDate',
		'cashInHand',
		'otherCurrentAssetName',
        'created_at',
        'updated_at',
       
    ];
}
