<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company_profile_checks extends Model
{
    use HasFactory;
    protected $fillable = [
        'userId',
        'comp_type','cin','inc_date','comp_pan_no','turnover_last_year',
        'trade_license','trade_license_input',
        'shop_est','shop_est_input',
        'prof_tax','prof_tax_input',
        'gst','gst_input',
        'buss_type','industry',
        'tan','tan_input',
        'msme','msme_input',
        'epf','epf_input',
        'esi','esi_input',
        'industry_cert','industry_cert_input',
        'fssai','fssai_input',
        'pollution_cert','pollution_cert_input',
        'iec','iec_input',
        'factory_license','factory_license_input',
        'fire_noc','fire_noc_input',
        'website','website_input',
        'hr_payroll','hr_payroll_input',
        'acc_soft','acc_soft_input',
        'erp_crm','erp_crm_input',
        'per_emp','con_emp',
        'sal_range_one','sal_range_two','sal_range_three',

        // checks + docs
        'inc_cert_chk','inc_cert_doc',
        'comp_pan_chk','comp_pan_doc',
        'trade_chk','trade_doc',
        'shop_est_chk','shop_est_doc',
        'ptax_chk','ptax_doc',
        'gst_chk','gst_doc',
        'tan_chk','tan_doc',
        'msme_chk','msme_doc',
        'epf_chk','epf_doc',
        'esi_chk','esi_doc',
        'ind_chk','ind_doc',
        'fssai_chk','fssai_doc',
        'poll_chk','poll_doc',
        'import_chk','import_doc',
        'fact_chk','fact_doc',
        'fire_chk','fire_doc',
		
		'financial_review',
		'tax_review',
		'compliance_review',
		'statutory_auditor',
		'bus_status',
		'kyc_din',
		'return_loan',
		'agm_status',
		'roc_status',
		'audit_report',
		'gst_status',
		'income_tax_status',
		'tds_status',
		'pf_esi_status',
		'trade_status',
		'ptax_status',
		'labour_law',
		'msme_status',
		'dpdp_act',
		'xbrl_filing',
		'intellectual_property',
		'risk_level',
		'priority_one',
		'priority_two',
		'priority_three',
		'specialist_review',
		'officer_name',
		'designation',
		'app_date',
		'admin_status',
		'approved_on',
		'admin_remark',
		'admin_certificate',
		'attempt_count',
		'attempt_year',
    ];
}
